def unicite_dico():
    '''
    Supprime dans le dictionnaire global les équipes en double.
    dico_global.keys() -> set(sico_global.keys()) 
    '''
    print('dico_global = {')
    for key in set(dico_global.keys()):
        print(f'"{key}":"{dico_global[key]}",')
    print('}')

dico_global = {
"MaccabiHaifa":"Maccabi Haifa",
"Alcorcon AD":"AD Alcorcon",
"Ludogorets Razgrad":"Ludogorets",
"Eintracht Francfort":"Eintracht Francfort",
"Roumanie":"Roumanie",
"Mexique":"Mexique",
"SCU Torreense":"Torreense",
"Lyon":"Lyon",
"CF Cadiz":"CF Cadiz",
"AtalantaBergame":"Atalanta",
"Werder Brême":"Werder Brême",
"PlymouthArgyle":"Plymouth Argyle",
"ParisFC":"Paris FC",
"Almería":"Almeria",
"Shakhtar Donetsk":"Shakhtar Donetsk",
"UDAlmeria":"Almeria",
"União de Leiria":"Uniao Leiria",
"BenficaLisbonne":"Benfica",
"Ajax":"Ajax Amsterdam",
"Sporting":"Sporting Portugal",
"BirminghamCity":"Birmingham",
"Ajax Amsterdam":"Ajax Amsterdam",
"Fribourg":"Fribourg",
"Servette":"Servette FC",
"Hannover 96":"Hanovre 96",
"Plymouth Argyle":"Plymouth Argyle",
"FC Cologne":"FC Cologne",
"Chaves":"Chaves",
"UniaoDeLeiria":"Uniao Leiria",
"Espanyol":"Espanyol Barcelone",
"Queens Park Rangers":"Queens Park Rangers",
"Queens Park R.":"Queens Park Rangers",
"ACReggiana":"Reggiana",
"LeixoesSC":"Leixoes SC",
"Espagne":"Espagne",
"Carthagene":"FC Cartagena",
"SlaviaPrague":"SlaviaPrague",
"Rennes":"Rennes",
"Rio Ave":"Rio Ave",
"IpswichTown":"Ipswich Town",
"Sporting Braga":"Braga",
"Galatasaray":"Galatasaray",
"Fulham":"Fulham",
"AC Feralpisalo":"AC Feralpisalo",
"Jamaïque":"Jamaïque",
"Avs Sad":"AVS Futebol SAD",
"AVS Futebol":"AVS Futebol SAD",
"SDEibar":"Eibar",
"Bolivie":"Bolivie",
"Paraguay":"Paraguay",
"Bosnie-Herzégovine":"Bosnie-Herzégovine",
"Estonie":"Estonie",
"Monza":"Monza",
"Sporting Gijon":"Gijon",
"Hongrie":"Hongrie",
"Quevilly-RouenMétropole":"Quevilly-Rouen",
"HansaRostock":"Hansa Rostock",
"LeedsUtd":"Leeds United",
"Ternana Calcio":"Ternana",
"Bordeaux":"Bordeaux",
"B.Leverkusen":"Leverkusen",
"Eintracht Braunschweig":"Eintracht Brunswick",
"Ukraine":"Ukraine",
"SCPaderborn07":"Paderborn",
"StPauli":"St. Pauli",
"VfL 1899 Osnabruck":"VfL Osnabrück",
"Wolfsbourg":"Wolfsbourg",
"SpVgg Elversberg 07":"SpVgg Elversberg 07",
"BenficaLisbonneB":"Benfica B",
"Stoke City":"Stoke City",
"QPR":"Queens Park Rangers",
"FCHeidenheim1846":"Heidenheim",
"Galles":"Pays de Galles",
"ManchesterCity":"Manchester City",
"Pisa SC":"Pisa",
"Real Saragosse":"Real Saragosse",
"CFVillarrealB":"Villarreal CF B",
"Uniao Leiria":"Uniao Leiria",
"Newcastle":"Newcastle",
"Cardiff":"Cardiff City",
"Wolfsburg":"Wolfsbourg",
"AvsFutebolSad":"AVS Futebol SAD",
"QueensParkRangers":"Queens Park Rangers",
"LegiaVarsovie":"Legia Varsovie",
"SturmGraz":"Sturm Graz",
"Laval":"Lavallois",
"Croatie":"Croatie",
"Auxerre":"Auxerre",
"Ascoli Picchio":"Ascoli",
"GD Estoril Praia":"Estoril",
"Man.City":"Manchester City",
"Schalke":"Schalke 04",
"ServetteGenève":"Servette FC",
"Burgos":"Burgos CF",
"Equateur":"Equateur",
"Coventry City":"Coventry City",
"Hertha Berlin":"Hertha Berlin",
"Amorebieta":"SD Amorebieta",
"Estrela":"CF Estrela Amadora",
"VeneziaFC":"Venise",
"SV Wehen":"SV Wehen Wiesbaden",
"AC Sparta Prague":"Sparta Prague",
"GrenobleFoot":"Grenoble",
"ParisSG":"PSG",
"Qarabag FK":"Qarabag Agdam",
"FCHeidenheim":"Heidenheim",
"Sunderland":"Sunderland",
"CDNacional":"Nacional Madeira",
"NacionalMadère":"Nacional Madeira",
"Nacional Madère":"Nacional Madeira",
"AVSFutebol":"AVS Futebol SAD",
"AVSFutebolSAD":"AVS Futebol SAD",
"Quevilly Rouen":"Quevilly-Rouen",
"UD Oliveirense":"Oliveirense",
"West Ham":"WestHam",
"Greuther Fürth":"Greuther Furth",
"Huddersfield Town":"Huddersfield T.",
"Karlsruher":"Karlsruhe",
"Viktoria Plzen":"ViktoriaPlzen",
"Bastia":"SC Bastia",
"Toulouse":"Toulouse",
"Leganes":"Leganes",
"CD Leganes":"Leganes",
"FCPortoB":"FC Porto B",
"Copenhague":"FC Copenhague",
"Birmingham C.":"Birmingham",
"Venise":"Venise",
"FC Séville":"FC Séville",
"West Bromwich":"West Bromwich",
"Milan AC":"Milan AC",
"Torreense":"Torreense",
"Ein.Francfort":"Eintracht Francfort",
"République tchèque":"République Tchèque",
"Pau":"Pau",
"HullCity":"Hull City",
"R.DeFerrol":"Racing Ferrol",
"Valladolid":"Real Valladolid",
"Feirense":"Feirense",
"Sampdoria Gênes":"Sampdoria Gênes",
"LaGantoise":"La Gantoise",
"WestBromwich":"West Bromwich",
"Lens":"Lens",
"Fenerbahçe":"Fenerbahce",
"Albacete":"Albacete",
"Southampton":"Southampton",
"Nantes":"Nantes",
"Bayern Munich":"Bayern Munich",
"Tenerife":"CD Tenerife",
"Francfort":"Eintracht Francfort",
"Ferencváros":"Ferencvaros",
"NottinghamF.":"Nottingham Forest",
"Nottingham F.":"Nottingham Forest",
"GironaFC":"Gérone",
"Rép.Tchèque":"République Tchèque",
"FC Andorra":"Andorra",
"HerthaBerlin":"Hertha Berlin",
"RayoVallecano":"Rayo Vallecano",
"CAOsasuna":"Osasuna",
"Racing Santander":"Racing Santander",
"HuddersfieldTown":"Huddersfield T.",
"Tchéquie":"République Tchèque",
"Club Bruges":"FC Bruges",
"SpeziaCalcio":"Spezia",
"SpeziaC.":"Spezia",
"Spezia C.":"Spezia",
"Casa Pia AC":"Casa Pia AC",
"Atalanta Bergame":"Atalanta",
"Torino":"Torino",
"DeportivoAlavés":"Alaves",
"MillwallFC":"Millwall FC",
"Nacional Madeira ":"Nacional Madeira",
"Almeria":"Almeria",
"Middlesbrough":"Middlesbrough FC",
"WehenWiesbaden":"SV Wehen Wiesbaden",
"AC Reggiana 1919":"Reggiana",
"Slovénie":"Slovénie",
"Cartagena":"FC Cartagena",
"Pologne":"Pologne",
"BlackburnRovers":"Blackburn",
"Bologne":"Bologne",
"FC Porto":"FC Porto",
"Borussia Mönchengladbach":"Borussia M'Gladbach",
"GranadaCF":"Grenade",
"Granada CF":"Grenade",
"FCPorto":"FC Porto",
"Greuther Furth":"Greuther Furth",
"Sheffield United":"Sheffield United",
"Rotherham":"Rotherham Unit",
"Finlande":"Finlande",
"CF Estrela Amadora":"CF Estrela Amadora",
"BenficaLisbonB":"Benfica B",
"Sheffield Wed.":"Sheffield Wednesday",
"Karlsruhe":"Karlsruhe",
"GrenadeCF":"Grenade",
"CádizCF":"CF Cadiz",
"BorussiaDortmund":"Dortmund",
"Lecco":"Calcio Lecco 1912",
"VfL Osnabruck":"VfL Osnabrück",
"Leeds":"Leeds United",
"UnionSaint-Gilloise":"Union Saint-Gilloise",
"FerencvarosiTC":"Ferencvaros",
"Dusseldorf":"Fortuna Dusseldorf",
"Aston Villa":"Aston Villa",
"SheffieldWednesday":"Sheffield Wednesday",
"AthleticBilbao":"Athletic Bilbao",
"Ath. Bilbao":"Athletic Bilbao",
"France":"France",
"CalcioLecco":"Calcio Lecco 1912",
"Mac.TelAviv":"Mac.TelAviv",
"Shakht.Donetsk":"Shakhtar Donetsk",
"Frosinone":"Frosinone",
"Watford":"Watford FC",
"Preston":"Preston North End",
"FrosinoneCalcio":"Frosinone",
"Estoril":"Estoril",
"Braunschweig":"Eintracht Brunswick",
"Estoril-Praia":"Estoril",
"Géorgie":"Géorgie",
"USSalernitana1919":"Salernitana",
"FC Vizela":"FC Vizela",
"FC Porto B":"FC Porto B",
"PAOK Salonique":"PAOKSalonique",
"Grenoble":"Grenoble",
"Pérou":"Pérou",
"Wehen":"SV Wehen Wiesbaden",
"Borussia M'Gladbach":"Borussia M'Gladbach",
"SportingGijon":"Gijon",
"StEtienne":"Saint-Etienne",
"Borussia Dortmund":"Dortmund",
"FCSüdtirol":"FC Sudtirol",
"Le Havre":"Le Havre",
"Cremonese":"Cremonese",
"Palerme":"Palerme",
"Molde":"Molde",
"Hull":"Hull City",
"Cardiff City":"Cardiff City",
"Modene":"Modène",
"FC Modène":"Modène",
"CF Os Belenenses":"CF Os Belenenses",
"LeHavre":"Le Havre",
"Famalicao":"Famalicao",
"Bristol City":"Bristol City",
"Inter":"Inter Milan",
"FC Hansa Rostock":"Hansa Rostock",
"Getafe":"Getafe",
"FC Sudtirol Bolzano":"FC Sudtirol",
"Guimaraes":"Vitoria Guimaraes",
"FC Heidenheim 1846":"Heidenheim",
"Real Sociedad":"Real Sociedad",
"Fortuna Düsseldorf":"Fortuna Dusseldorf",
"FKLudogorets":"Ludogorets",
"Ipswich":"Ipswich Town",
"Metz":"Metz",
"Wolverhampton":"Wolverhampton",
"ASBari":"Bari",
"HellasVérone":"Hellas Vérone",
"Leixões":"Leixoes SC",
"Marseille":"Marseille",
"Maccabi Haifa":"Maccabi Haifa",
"ParmeFC":"Parme",
"Paderborn":"Paderborn",
"RealMadrid":"Real Madrid",
"SV Wehen Wiesbaden":"SV Wehen Wiesbaden",
"Boavista":"Boavista",
"RB Leipzig":"RB Leipzig",
"BosnieHerzég.":"Bosnie-Herzégovine",
"FCSudtirol":"FC Sudtirol",
"Viseu":"Viseu",
"Racing Club de Ferrol":"Racing Ferrol",
"RealMajorque":"Majorque",
"UDOliveirense":"Oliveirense",
"Colombie":"Colombie",
"EstorilPraia":"Estoril",
"Paris FC":"Paris FC",
"YoungBoysBerne":"Young Boys Berne",
"Regensburg":"Jahn Regensburg",
"BristolCity":"Bristol City",
"Montpellier":"Montpellier",
"Rodez":"Rodez",
"Bournemouth":"Bournemouth",
"CardiffCity":"Cardiff City",
"Ath.Bilbao":"Athletic Bilbao",
"Venezia FC":"Venise",
"Rayo Vallecano":"Rayo Vallecano",
"SportingFarense":"Farense",
"SC Farense":"Farense",
"Manchester United":"Manchester United",
"AVS Futebol SAD":"AVS Futebol SAD",
"Turquie":"Turquie",
"Boavista FC":"Boavista",
"Legia Varsovie":"Legia Varsovie",
"Nacional da Madeir":"Nacional Madeira",
"Cologne":"FC Cologne",
"SlovanBratislava":"Slovan Bratislava",
"HellasVerone":"Hellas Vérone",
"Maritimo":"Maritimo",
"BayerLeverkusen":"Leverkusen",
"Monaco":"Monaco",
"Mirandes":"CD Mirandes",
"PacosFerreira":"Pacos de Ferreira",
"Coventry":"Coventry City",
"DinamoZagreb":"Dinamo Zagreb",
"CFEstrela":"CF Estrela Amadora",
"Fenerbahce":"Fenerbahce",
"ClubDepEldense":"Club Deportivo Eldense",
"Club Eldense":"Club Deportivo Eldense",
"ManchesterUtd":"Manchester United",
"FCAndorra":"Andorra",
"Slovaquie":"Slovaquie",
"États-Unis":"États-Unis",
"Cosenza":"Nuova Cosenza Calcio",
"ClubBruges":"FC Bruges",
"Famalicão":"Famalicao",
"Quevilly-Rouen":"Quevilly-Rouen",
"CD Santa Clara":"Santa Clara",
"RealSaragosse":"Real Saragosse",
"ServetteFC":"Servette FC",
"CDTenerife":"CD Tenerife",
"USLecce":"Lecce",
"FCMagdeburg":"Magdebourg",
"FC Magdeburg":"Magdebourg",
"Nuova Cosenza Calcio":"Nuova Cosenza Calcio",
"QarabagFK":"Qarabag Agdam",
"Juventus":"Juventus Turin",
"Espanyol Barcelone":"Espanyol Barcelone",
"Sporting Portugal":"Sporting Portugal",
"SDHuesca":"SD Huesca",
"QueensParkR.":"Queens Park Rangers",
"Empoli":"Empoli",
"CD Feirense":"Feirense",
"FC Sudtirol":"FC Sudtirol",
"Crystal Palace":"Crystal Palace",
"FC Viktoria Plzen":"ViktoriaPlzen",
"FC Barcelone":"FC Barcelone",
"Man.United":"Manchester United",
"Ascoli":"Ascoli",
"Rodez Aveyron Football":"Rodez",
"Caen":"Caen",
"Juventus Turin":"Juventus Turin",
"Israël":"Israël",
"VitoriaGuimaraes":"Vitoria Guimaraes",
"Alaves":"Alaves",
"FCViktoriaPlzen":"ViktoriaPlzen",
"Sporting Farense":"Farense",
"CeltaVigo":"Celta Vigo",
"Andorra":"Andorra",
"Feyenoord Rotterdam":"Feyenoord",
"Chili":"Chili",
"Modena FC":"Modène",
"WestHam":"WestHam",
"Kaiserslautern":"Kaiserslautern",
"Suisse":"Suisse",
"PAOK FC":"PAOKSalonique",
"Benfica B":"Benfica B",
"SportingdeGijón":"Gijon",
"Etats-Unis":"États-Unis",
"Venezia":"Venise",
"Eibar":"Eibar",
"Atalanta":"Atalanta",
"InterMilan":"Inter Milan",
"Slavia Prague":"SlaviaPrague",
"Serbie":"Serbie",
"Bodø/Glimt":"Bodø/Glimt",
"Bodoe/Glimt":"Bodø/Glimt",
"Liverpool":"Liverpool",
"AdAlcorcon":"AD Alcorcon",
"M'Gladbach":"Borussia M'Gladbach",
"Guingamp":"Guingamp",
"BurgosCF":"Burgos CF",
"Come":"Côme",
"FortunaDüsseldorf":"Fortuna Dusseldorf",
"Strasbourg":"Strasbourg",
"Estrela Amadora":"CF Estrela Amadora",
"PAOKSalonique":"PAOKSalonique",
"Chelsea":"Chelsea",
"Reggiana":"Reggiana",
"Hambourg":"Hambourg",
"Darmstadt 98":"Darmstadt",
"SV Darmstadt":"Darmstadt",
"AnnecyFC":"Annecy",
"République Tchèque":"République Tchèque",
"La Gantoise":"La Gantoise",
"Racing Ferrol":"Racing Ferrol",
"Barcelone":"FC Barcelone",
"Danemark":"Danemark",
"AD Alcorcon":"AD Alcorcon",
"LeedsUnited":"Leeds United",
"Atl. Madrid":"Atletico Madrid",
"AtléticoMadrid":"Atletico Madrid",
"Atlético Madrid":"Atletico Madrid",
"HamburgerSV":"Hambourg",
"BoavistaFC":"Boavista",
"AlbaceteBalompie":"Albacete",
"EintrachtBraunschweig":"Eintracht Brunswick",
"GreutherFurth":"Greuther Furth",
"Club Deportivo Eldense":"Club Deportivo Eldense",
"Bodo/Glimt":"Bodø/Glimt",
"CDLeganes":"Leganes",
"Canada":"Canada",
"Cadiz CF":"CF Cadiz",
"Sankt-Pauli":"St. Pauli",
"Villarreal":"Villarreal",
"Sporting CP":"Sporting Portugal",
"VfB Stuttgart":"VfB Stuttgart",
"FC Cartagena":"FC Cartagena",
"ACPisa1909":"Pisa",
"AC Pisa 1909":"Pisa",
"Scu Torreense":"Torreense",
"FCCopenhague":"FC Copenhague",
"Osasuna":"Osasuna",
"GD Chaves":"Chaves",
"Rotherham United":"Rotherham Unit",
"Burnley":"Burnley FC",
"Quevilly - Rouen":"Quevilly-Rouen",
"Côme":"Côme",
"BSC Young Boys":"Young Boys Berne",
"Pise":"Pisa",
"Como1907":"Côme",
"UnionBerlin":"Union Berlin",
"Lille":"Lille",
"Angers":"Angers",
"CFOsBelenenses":"CF Os Belenenses",
"Huesca":"SD Huesca",
"Annecy FC":"Annecy",
"Augsburg":"Augsbourg",
"Uniao de Leiria":"Uniao Leiria",
"Gil Vicente":"Gil Vicente",
"St. Pauli":"St. Pauli",
"Séville":"FC Séville",
"Roma":"AS Rome",
"Villarreal CF B":"Villarreal CF B",
"Birmingham City":"Birmingham",
"Como":"Côme",
"Gerone":"Gérone",
"Lank FC Vilaverdense":"Vilaverdense",
"Spezia":"Spezia",
"FCPenafiel":"Penafiel",
"Sudtirol":"FC Sudtirol",
"RealBetis":"Betis Séville",
"PSV Eindhoven":"PSV Eindhoven",
"Belenenses":"CF Os Belenenses",
"Catanzaro":"US Catanzaro",
"CD Tondela":"CD Tondela",
"Millwall FC":"Millwall FC",
"Betis":"Betis Séville",
"MaccabiTelAviv":"Mac.TelAviv",
"Hellas Vérone":"Hellas Vérone",
"SC Bastia":"SC Bastia",
"CasaPia":"Casa Pia AC",
"HolsteinKiel":"Holstein Kiel",
"CostaRica":"Costa Rica",
"Qarabag Agdam":"Qarabag Agdam",
"Vizela":"FC Vizela",
"Como 1907":"Côme",
"Magdebourg":"Magdebourg",
"Plym. Argyle":"Plymouth Argyle",
"B.M'gladbach":"Borussia M'Gladbach",
"Panama":"Panama",
"NorwichCity":"Norwich",
"AC Reggiana":"Reggiana",
"Eldense":"Club Deportivo Eldense",
"SVDarmstadt":"Darmstadt",
"Rangers":"Rangers",
"CDEldense":"Club Deportivo Eldense",
"BoavistaPorto":"Boavista",
"FCGilVicente":"Gil Vicente",
"EspanyolBarcelone":"Espanyol Barcelone",
"Santa Clara":"Santa Clara",
"Luton Town":"Luton Town",
"Lazio Rome":"Lazio Rome",
"Celta Vigo":"Celta Vigo",
"Südtirol":"FC Sudtirol",
"ADAlcorcon":"AD Alcorcon",
"GreutherFürth":"Greuther Furth",
"Modena":"Modène",
"SV Elversberg":"SpVgg Elversberg 07",
"Grenoble Foot":"Grenoble",
"CasaPiaAtletico":"Casa Pia AC",
"FCCologne":"FC Cologne",
"CD Mafra":"CD Mafra",
"Mafra":"CD Mafra",
"Troyes":"Troyes",
"Milan":"Milan AC",
"Tenerife CD":"CD Tenerife",
"Ludogorets":"Ludogorets",
"Academico de Viseu":"Viseu",
"Portimonense":"Portimonense",
"CSMaritimo":"Maritimo",
"Moreirense FC":"Moreirense",
"Valence":"Valencia",
"CF Valence":"Valencia",
"PSG":"PSG",
"Hanovre 96":"Hanovre 96",
"US Catanzaro":"US Catanzaro",
"PaçosFerreira":"Pacos de Ferreira",
"BrentfordFC":"Brentford",
"Alcorcon":"AD Alcorcon",
"Atl.Madrid":"Atletico Madrid",
"Athletic Bilbao":"Athletic Bilbao",
"Luxembourg":"Luxembourg",
"AcademicoViseu":"Viseu",
"Dinamo Zagreb":"Dinamo Zagreb",
"BurnleyFC":"Burnley FC",
"FCVizela":"FC Vizela",
"Porto":"FC Porto",
"Salernitana":"Salernitana",
"Villarreal B":"Villarreal CF B",
"Estoril Praia":"Estoril",
"Qarabağ":"Qarabag Agdam",
"CrystalPalace":"Crystal Palace",
"LudogoretsRazgrad":"Ludogorets",
"FC Copenhague":"FC Copenhague",
"Grèce":"Grèce",
"WerderBrême":"Werder Brême",
"SSVJahnRegensburg":"Jahn Regensburg",
"Frosinone Calcio":"Frosinone",
"Vilaverdense":"Vilaverdense",
"Leixoes SC":"Leixoes SC",
"Servette FC":"Servette FC",
"Manchester City":"Manchester City",
"Man. City":"Manchester City",
"RealSociedad":"Real Sociedad",
"LutonTown":"Luton Town",
"CFValence":"Valencia",
"FC Penafiel":"Penafiel",
"Reggiana 1919":"Reggiana",
"CF Estrela":"CF Estrela Amadora",
"ACReggiana1919":"Reggiana",
"Modène":"Modène",
"Atletico Madrid":"Atletico Madrid",
"Autriche":"Autriche",
"Calcio Lecco 1912":"Calcio Lecco 1912",
"Plymouth":"Plymouth Argyle",
"FC St. Pauli":"St. Pauli",
"St Pauli":"St. Pauli",
"Mayence":"Mayence",
"Stoke":"Stoke City",
"FC Carthagène":"FC Cartagena",
"Union Saint Gilloise":"Union Saint-Gilloise",
"Ecosse":"Écosse",
"Sparta Prague":"Sparta Prague",
"Brésil":"Brésil",
"Parme":"Parme",
"RealOviedo":"Real Oviedo",
"Augsbourg":"Augsbourg",
"Ternana":"Ternana",
"Hull City":"Hull City",
"Elche":"Elche",
"Norwich":"Norwich",
"Saint-Étienne":"Saint-Etienne",
"Ipswich Town":"Ipswich Town",
"FC Annecy":"Annecy",
"Glasgow Rangers":"Rangers",
"VillarrealCF":"Villarreal",
"VfbStuttgart":"VfB Stuttgart",
"GilVicente":"Gil Vicente",
"Union Berlin":"Union Berlin",
"1.FCMagdeburg":"Magdebourg",
"Marítimo":"Maritimo",
"Norwich City":"Norwich",
"Grenade":"Grenade",
"Académico Viseu":"Viseu",
"Dortmund":"Dortmund",
"Feralpisalo":"AC Feralpisalo",
"Saint-Etienne":"Saint-Etienne",
"SantaClara":"Santa Clara",
"RacingSantander":"Racing Santander",
"PSVEindhoven":"PSV Eindhoven",
"Academico Viseu":"Viseu",
"Leicester":"Leicester",
"FeyenoordRotterdam":"Feyenoord",
"Nottingham Forest":"Nottingham Forest",
"Real Madrid":"Real Madrid",
"Preston North End":"Preston North End",
"Lazio":"Lazio Rome",
"Lecce":"Lecce",
"UniaoLeiria":"Uniao Leiria",
"Annecy":"Annecy",
"NottinghamForest":"Nottingham Forest",
"Schalke 04":"Schalke 04",
"CDTondela":"CD Tondela",
"BetisSéville":"Betis Séville",
"Hellas Verone":"Hellas Vérone",
"Portimonense SC":"Portimonense",
"ViktoriaPlzen":"ViktoriaPlzen",
"Sturm Graz":"Sturm Graz",
"Portugal":"Portugal",
"StokeCity":"Stoke City",
"Farense":"Farense",
"Bochum":"Bochum",
"Darmstadt":"Darmstadt",
"Jahn Regensburg":"Jahn Regensburg",
"Sampdoria":"Sampdoria Gênes",
"Kazakhstan":"Kazakhstan",
"Valenciennes":"Valenciennes",
"Real Valladolid":"Real Valladolid",
"Brest":"Brest",
"USCremonese":"Cremonese",
"US Cremonese":"Cremonese",
"Naples":"Naples",
"Gijon":"Gijon",
"Oliveirense":"Oliveirense",
"Reims":"Reims",
"AC Monza":"Monza",
"Fiorentina":"Fiorentina",
"ValenceCF":"Valencia",
"Argentine":"Argentine",
"Quevilly":"Quevilly-Rouen",
"CS Maritimo":"Maritimo",
"SCFarense":"Farense",
"SVWehenWiesbaden":"SV Wehen Wiesbaden",
"USCatanzaro":"US Catanzaro",
"Pisa":"Pisa",
"Blackburn":"Blackburn",
"Braga":"Braga",
"FeralpiSalò":"AC Feralpisalo",
"Dunkerque":"Dunkerque",
"Islande":"Islande",
"Uruguay":"Uruguay",
"ElcheCF":"Elche",
"Swansea City":"Swansea City",
"Sl Benfica B":"Benfica B",
"Paris SG":"PSG",
"Pacos de Ferreira":"Pacos de Ferreira",
"Spezia Calcio":"Spezia",
"Leverkusen":"Leverkusen",
"Bayer Leverkusen":"Leverkusen",
"Real Oviedo":"Real Oviedo",
"Vitoria Guimaraes":"Vitoria Guimaraes",
"Young Boys Berne":"Young Boys Berne",
"Costa Rica":"Costa Rica",
"Gil Vicente FC":"Gil Vicente",
"Casa Pia Lisbon":"Casa Pia AC",
"Nacional":"Nacional Madeira",
"VFL Bochum":"Bochum",
"Benfica":"Benfica",
"Birmingham":"Birmingham",
"Hanovre96":"Hanovre 96",
"Moreirense":"Moreirense",
"St.Pauli":"St. Pauli",
"Rotherham Unit":"Rotherham Unit",
"Eintracht Brunswick":"Eintracht Brunswick",
"BenficaB":"Benfica B",
"BayernMunich":"Bayern Munich",
"Leixoes":"Leixoes SC",
"Hoffenheim":"TSG Hoffenheim",
"RotherhamUnited":"Rotherham Unit",
"VilaverdenseFC":"Vilaverdense",
"Clermont":"Clermont",
"JahnRegensburg":"Jahn Regensburg",
"RioAve":"Rio Ave",
"Hambourg SV":"Hambourg",
"Nuremberg":"Nuremberg",
"QuevillyRouen":"Quevilly-Rouen",
"Genoa":"Genoa",
"USA":"États-Unis",
"Ferencvaros":"Ferencvaros",
"VillarrealB":"Villarreal CF B",
"Gérone":"Gérone",
"Académico de Viseu":"Viseu",
"Nice":"Nice",
"ASRome":"AS Rome",
"Nacional Funchal":"Nacional Madeira",
"Qarabag":"Qarabag Agdam",
"Schalke04":"Schalke 04",
"Porto B":"FC Porto B",
"SportingCP":"Sporting Portugal",
"TSG Hoffenheim":"TSG Hoffenheim",
"Maccabi Tel Aviv":"Mac.TelAviv",
"CDMirandes":"CD Mirandes",
"Allemagne":"Allemagne",
"GlasgowRangers":"Rangers",
"FCBruges":"FC Bruges",
"FortunaDusseldorf":"Fortuna Dusseldorf",
"FCFamalicao":"Famalicao",
"Fortuna Dusseldorf":"Fortuna Dusseldorf",
"Brescia":"Brescia",
"Vénézuela":"Vénézuela",
"Arouca":"FC Arouca",
"Millwall":"Millwall FC",
"SVElversberg":"SpVgg Elversberg 07",
"Slo.Bratislava":"Slovan Bratislava",
"Quevilly-Rouen Métropole":"Quevilly-Rouen",
"Pacos Ferreira":"Pacos de Ferreira",
"TernanaCalcio":"Ternana",
"Casa Pia":"Casa Pia AC",
"RealBurgos":"Burgos CF",
"FCNuremberg":"Nuremberg",
"FC Nuremberg":"Nuremberg",
"Burgos CF":"Burgos CF",
"Cittadella":"Cittadella",
"Lorient":"Lorient",
"RBLeipzig":"RB Leipzig",
"ACAjaccio":"AC Ajaccio",
"Saint-Gilloise":"Union Saint-Gilloise",
"AjaxAmsterdam":"Ajax Amsterdam",
"UDLasPalmas":"Las Palmas",
"Olympiakos":"Olympiakos",
"VfL Osnabrück":"VfL Osnabrück",
"Ajaccio":"AC Ajaccio",
"Stuttgart":"VfB Stuttgart",
"FC Arouca":"FC Arouca",
"Tottenham":"Tottenham",
"PaysdeGalles":"Pays de Galles",
"SheffieldUnited":"Sheffield United",
"Sheffield Utd":"Sheffield United",
"PortimonenseSC":"Portimonense",
"Luton":"Luton Town",
"Vérone":"Hellas Vérone",
"EintrachtFrancfort":"Eintracht Francfort",
"PrestonNorthEnd":"Preston North End",
"Brighton":"Brighton Hove",
"Brighton Hove":"Brighton Hove",
"Angleterre":"Angleterre",
"LasPalmas":"Las Palmas",
"NacionalMadeira":"Nacional Madeira",
"ShakhtarDonetsk":"Shakhtar Donetsk",
"Holstein Kiel":"Holstein Kiel",
"Swansea":"Swansea City",
"St Etienne":"Saint-Etienne",
"Paços De Ferreira":"Pacos de Ferreira",
"US Concarneau":"Concarneau",
"SDAmorebieta":"SD Amorebieta",
"RépubliqueTchèque":"République Tchèque",
"SD Amorebieta":"SD Amorebieta",
"Middlesbrough FC":"Middlesbrough FC",
"JuventusTurin":"Juventus Turin",
"Leeds United":"Leeds United",
"Leeds Utd":"Leeds United",
"WestBromwichAlbion":"West Bromwich",
"Bari":"Bari",
"Udinese":"Udinese",
"LevanteUD":"Levante",
"CDMafra":"CD Mafra",
"GetafeCF":"Getafe",
"Santander":"Racing Santander",
"Écosse":"Écosse",
"Betis Séville":"Betis Séville",
"Ferrol":"Racing Ferrol",
"NuovaCosenza":"Nuova Cosenza Calcio",
"Nuova Cosenza":"Nuova Cosenza Calcio",
"Wehen Wiesbaden":"SV Wehen Wiesbaden",
"Vitória Guimarães":"Vitoria Guimaraes",
"Heidenheim":"Heidenheim",
"FC Heidenheim":"Heidenheim",
"Osnabrück":"VfL Osnabrück",
"SCUTorreense":"Torreense",
"Brentford":"Brentford",
"Équateur":"Equateur",
"Vitoria SC Guimaraes":"Vitoria Guimaraes",
"ASCittadella":"Cittadella",
"ClubEldense":"Club Deportivo Eldense",
"Avs Futebol Sad":"AVS Futebol SAD",
"YoungBoys":"Young Boys Berne",
"PAOK":"PAOKSalonique",
"Düsseldorf":"Fortuna Dusseldorf",
"Arsenal":"Arsenal",
"BrightonHove":"Brighton Hove",
"Sheffield Wednesday":"Sheffield Wednesday",
"Pays de Galles":"Pays de Galles",
"Italie":"Italie",
"SpartaPrague":"Sparta Prague",
"Union Saint-Gilloise":"Union Saint-Gilloise",
"ACMonza":"Monza",
"Huddersfield":"Huddersfield T.",
"SheffieldUtd":"Sheffield United",
"AstonVilla":"Aston Villa",
"FC Pacos Ferreira":"Pacos de Ferreira",
"Penafiel":"Penafiel",
"Venezuela":"Vénézuela",
"Saragosse":"Real Saragosse",
"Magdeburg":"Magdebourg",
"Blackburn Rovers":"Blackburn",
"SheffieldWed.":"Sheffield Wednesday",
"Pays-Bas":"Pays-Bas",
"LazioRome":"Lazio Rome",
"Elversberg":"SpVgg Elversberg 07",
"AC Ajaccio":"AC Ajaccio",
"Tondela":"CD Tondela",
"Las Palmas":"Las Palmas",
"CD Nacional":"Nacional Madeira",
"Amiens":"Amiens",
"FCBarcelone":"FC Barcelone",
"Cadix":"CF Cadiz",
"Nacional Madeira":"Nacional Madeira",
"CSMaritimoMadeira":"Maritimo",
"Majorque":"Majorque",
"MilanAC":"Milan AC",
"Hansa Rostock":"Hansa Rostock",
"Belgique":"Belgique",
"Feyenoord":"Feyenoord",
"AS Rome":"AS Rome",
"RacingFerrol":"Racing Ferrol",
"Preston N. End":"Preston North End",
"Inter Milan":"Inter Milan",
"RealValladolid":"Real Valladolid",
"Levante":"Levante",
"FCQarabag":"Qarabag Agdam",
"Carthagène":"FC Cartagena",
"West Brom":"West Bromwich",
"BorussiaMönchengladbach":"Borussia M'Gladbach",
"FCSéville":"FC Séville",
"Ferencvárosi":"Ferencvaros",
"Sassuolo":"Sassuolo",
"AtleticoMadrid":"Atletico Madrid",
"AtleticodeMadrid":"Atletico Madrid",
"NuovaCosenzaCalcio":"Nuova Cosenza Calcio",
"CoventryCity":"Coventry City",
"Hanovre":"Hanovre 96",
"Man. United":"Manchester United",
"ManchesterUnited":"Manchester United",
"MaccabiTel-Aviv":"Mac.TelAviv",
"Concarneau":"Concarneau",
"UD Leiria":"Uniao Leiria",
"Everton":"Everton",
"Albanie":"Albanie",
"Cagliari":"Cagliari",
"Jamaique":"Jamaïque",
"Slovan Bratislava":"Slovan Bratislava",
"FCSB": "Fotbal Club Steaua Bucarest FCSB",
"FCSB ": "Fotbal Club Steaua Bucarest FCSB",
"AZ": "AZ Alkmaar",
"AZ Alkmaar": "AZ Alkmaar",
"AZAlkmaar":"AZ Alkmaar",
"Panathinaikos":"Panathinaikos",
"Panathinaïkos":"Panathinaikos",
"Jagiellonia Białystok":"Jagiellonia Białystok",
"JagielloniaBialystok":"Jagiellonia Białystok",
"Jagiellonia":"Jagiellonia Białystok",
"Jagiellonia Bialystok":"Jagiellonia Białystok",
"Pafos":"Pafos FC",
"PafosFC":"Pafos FC",
"Pafos FC":"Pafos FC",
"NKCelje":"NK Celje",
"NK CM Celje":"NK Celje",
"Celje":"NK Celje",
"NK Celje":"NK Celje",
"BoracBanjaLuka":"FK Borac Banja Luka",
"Borac Banja Luka":"FK Borac Banja Luka",
"FK Borac Banja Luka":"FK Borac Banja Luka",
"FCMartigues":"FC Martigues",
"Martigues":"FC Martigues",
"FC Martigues":"FC Martigues",
"RedStar":"Red Star FC",
"Red Star":"Red Star FC",
"Red Star FC":"Red Star FC",
"CD Castellon":"Club Deportivo Castellón",
"Castellon":"Club Deportivo Castellón",
"Castellón":"Club Deportivo Castellón",
"Malaga":"Málaga Club de Fútbol",
"Malaga CF":"Málaga Club de Fútbol",
"Cordoue":"Córdoba Club de Fútbol",
"Cordoba":"Córdoba Club de Fútbol",
"Deportivo":"Deportivo La Corogne",
"La Corogne":"Deportivo La Corogne",
"LaCorogne":"Deportivo La Corogne",
"Deportivo La Corogne":"Deportivo La Corogne",
"SC Pr Münster":"SC Preußen Münster",
"Münster":"SC Preußen Münster",
"SC Preussen Munster":"SC Preußen Münster",
"Preussen Münster":"SC Preußen Münster",
"SCPrMünster":"SC Preußen Münster",
"SC Preussen Münster":"SC Preußen Münster",
"Ulm1846":"SSV Ulm 1846 Fußball",
"SSV Ulm 1846":"SSV Ulm 1846 Fußball",
"SSVUlm1846":"SSV Ulm 1846 Fußball",
"SSV Ulm":"SSV Ulm 1846 Fußball",
"Arminia":"DSC Arminia Bielefeld",
"Arminia Bielefeld":"DSC Arminia Bielefeld",
"Bielefeld":"DSC Arminia Bielefeld",
"OxfordUnited":"Oxford United Football Club",
"Oxford":"Oxford United Football Club",
"Oxford United":"Oxford United Football Club",
"Derby":"Derby County FC",
"Derby County":"Derby County FC",
"Cesena":"Cesena",
"Juve Stabia":"Società Sportiva Juve Stabia",
"JuveStabia":"Società Sportiva Juve Stabia",
"Carrarese":"Carrarese Calcio",
"CarrareseC.":"Carrarese Calcio",
"Carrarese C.":"Carrarese Calcio",
"ACMantova":"Mantova 1911",
"Mantova":"Mantova 1911",
"Felgueiras":"Felgueiras",
"FC Felgueiras":"Felgueiras",
"FC Felgueiras 1932":"Felgueiras",
"FCFelgueiras":"Felgueiras",
"Felgueiras 1932":"Felgueiras",
"Alverca":"Alverca",
"FC Alverca":"Alverca",
"AlvercaFC":"Alverca",
"Alverca FC":"Alverca",
"FC Alverca SAD":"Alverca",
"CercleBruges":"Cercle Bruges",
"Cercle Bruges":"Cercle Bruges",
"Djurgardens":"Djurgardens",
"Djurgårdens":"Djurgardens",
"Djurgardens IF":"Djurgardens",
"Lugano":"Lugano",
"FC Lugano":"FC Lugano",
"FCLugano":"Lugano",
"RapidVienne":"Rapid Vienne",
"Rapid Vienne":"Rapid Vienne",
"SK Rapid":"Rapid Vienne",
"Portsmouth":"Portsmouth",
"Portsmouth FC":"Portsmouth",
"Cannes":"Cannes",
"Stade Briochin":"Stade Briochin",
"Saint Brieuc":"Stade Briochin",
"SaintBrieuc":"Stade Briochin",
"StadeBriochin":"Stade Briochin",
}